### ISSUE TITLE
Error Message: Class 'League\OAuth2\Client\Provider\GenericProvider' not found

### ISSUE THREAD

**Issue by virenbpanchal** [jespinal/ciqb-integration#3]
```
An uncaught Exception was encountered
Type: Error
Message: Class 'League\OAuth2\Client\Provider\GenericProvider' not found
Filename: C:\wamp64\www\CIQB\application\controllers\Qb_oauth_endpoint.php
Line Number: 33
Backtrace:
File: C:\wamp64\www\CIQB\index.php
Line: 315
Function: require_once
```
I have loaded autoload.php as below. 
`$config['composer_autoload'] = '../vendor/autoload.php';`

Below is my project structure.

I am working in localhost.

![ciqb structure](https://user-images.githubusercontent.com/38627232/53824682-24d36e80-3f3a-11e9-8c19-95069701f478.png)

Can you please guide me?

**Comment by jespinal** [comment]
Hello, @virenbpanchal :

Thanks for your patience. I'm not sure how Windows manages paths, but it might worth trying to specify the full path to the `autoload.php` file. If it works, then you would just need to indicate the correct relative path to it.

Also, I'll revisit the steps in order to get sure that Intuit didn't change anything in terms of class names, etc. That might also be a possible reason for the error.

**Comment by timburks2392** [comment]
I am still receiving the error listed above no matter what I do.. I have the same file structure as the user listed above but I'm still receiving this error after clicking the Connect Button
![image](https://user-images.githubusercontent.com/64570555/80668285-1366f300-8a67-11ea-99b0-007624962ab3.png)

**Comment by jespinal** [comment]
Hello, @timburks2392 : I just made a reassessment of the README file in order to get sure everything works as described. You might want to take a look at it in order to know if you missed some detail.

**Comment by mihirrana10** [comment]
am still receiving the error listed above no matter what I do.. I have the same file structure as the user listed above but I'm still receiving this error after clicking the Connect Button
<img width="960" alt="image" src="https://github.com/jespinal/ciqb-integration/assets/83169122/c691b841-d0d5-4502-b272-c903b22e08e2">
